[package]
name = "rust-wasm-action"
description = "Rust-generated WebAssembly GitHub action template"
version = "1.0.0"
repository = "https://github.com/peter-evans/rust-wasm-action"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
actions-toolkit-bindings = { path = "actions-toolkit-bindings" }
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = "0.3.56"
wasm-bindgen = "0.2.79"

[profile.release]
lto = true
